config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  root to: 'games#index'

  get '/posts/tags/:tag' => 'posts#index', as: :posts_tag
  get '/posts/new' => 'posts#new', as: :new_post
  post '/posts' => 'posts#create'
  get '/post/:id' => 'posts#show', as: :post
  delete '/post/:id' => 'posts#destroy'
  get '/post/:id/edit' => 'posts#edit', as: :edit_post
  patch '/post/:id' => 'posts#update'

  get '/gearvr' => 'games#index', as: :games
  get '/gearvr/new' => 'games#new', as: :new_game
  post '/gearvr' => 'games#create'
  get '/gearvr/:id' => 'games#show', as: :game
  get '/gearvr/:id/edit' => 'games#edit', as: :edit_game
  patch '/gearvr/:id' => 'games#update'
  delete '/gearvr/:id' => 'games#destroy'
  get '/add_genre/:genre' => 'games#add_genre', as: :add_genre

  get 'gearvr/developer/:developer' => 'developers#show', as: :developer

  get '/about-vrmachine' => 'pages#about'
  

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :attachments
  accepts_nested_attributes_for :attachments

  acts_as_taggable
  acts_as_taggable_on :genres

  ratyrate_rateable "rating"

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_attached_file :main_image, styles: { large: "1555×1037", medium: "394x262#" }
  validates_attachment_content_type :main_image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_attached_file :thumbnail
  validates_attachment_content_type :thumbnail, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  
  validates_uniqueness_of :name


  def self.latest
    order('date_developed DESC')
  end

  def full_url
    if !website.include?('http')
      "http://#{self.website}"
    else
      self.website
    end
  end

  def dollar_price
    "$#{price}"
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :genres, only: [:new, :edit]
  before_action :redirect_if_not_admin, only: [:new, :edit, :destroy]

  def new
    @game = Game.new
  end

  def index
    page = check_page

    if !params[:genres] && !params[:categories]
      @games = Game.paginate(:page => page, :per_page => 6).latest
      respond_to do |format|
        format.js { render layout: false }
        format.html
      end
    else
      if !params[:genres]
        @games = Game.where(category: params[:categories]).paginate(:page => page, :per_page => 6).latest
      elsif !params[:categories]
        @games = Game.tagged_with(params[:genres]).paginate(:page => page, :per_page => 6).latest
      else
        @games = Game.where(category: params[:categories]).tagged_with(params[:genres]).paginate(:page => page, :per_page => 6).latest
      end
      respond_to do |format|
        format.js { render layout: false }
        format.html
      end
    end
  end

  def link_index
    @games = Game.all
  end

  def create
    @game = Game.new(game_params)

    if @game.save
      if params[:game][:attachment]
        params[:game][:attachment][:image].each do |image|
          @game.attachments.create(image: image)
        end
      end
      redirect_to @game
    else
      render :new
    end
  end

  def show
    @game = Game.friendly.find(params[:id])
    @youtube_videos = @game.youtube_videos.split if !@game.youtube_videos.nil?
    @tags_list = @game.genre_list.split(',')[0]

    #filter genre list - features/genres/free(paid)
    features = ['free', 'paid', 'single-player', 'multi-player', 'internet-required', 'gamepad-required', 'gamepad-support', 'touchpad-support']

    @price_tag = @tags_list.include?('free') ? 'free' : 'paid'
    @genre_tags = (@tags_list - features)
    @feature_tags = @tags_list.select { |genre| features.include?(genre) } - ['free', 'paid']
    render layout: 'full-width'
  end

  def edit
    @game = Game.friendly.find(params[:id])
  end

  def update
    @game = Game.friendly.find(params[:id])
    if @game.update(game_params)
      if params[:game][:attachment]
        params[:game][:attachment][:image].each do |image|
          @game.attachments.create(image: image)
        end
      end
    end
    redirect_to @game
  end

  def destroy
    @game = Game.friendly.find(params[:id])
    if @game.destroy
      redirect_to games_path
    end
  end

  def add_genre
    @genre = params[:genre]
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  private

  def game_params
    params.require(:game).permit(:name, :date_developed, :detail, :developer, :genre_list, :category, :main_image, :thumbnail, :website, :price, :youtube_videos)
  end

  def genres
    @genres = %w(action simulation educational horror adventure exploration rpg casual puzzle narrative arcade shooter movie music video utilities sports productivity music arcade racing fighting strategy).sort
  end

  def check_page
    p = params[:page].to_i
    p > 1 ? p : 1
  end

  def redirect_if_not_admin
    redirect_to root_url if current_user && current_user.email != 'yangsunwoo@gmail.com'
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_filter.haml
%h2.checkbox-title Category

.checkbox-wrapper.checked
  = check_box_tag 'categories[]', "game", true, class: 'checkbox-filter categories'
  = label_tag :game, "<span></span>game".html_safe, class: 'checkbox-label'

.checkbox-wrapper.checked
  = check_box_tag 'categories[]', "entertainment", true, class: 'checkbox-filter categories'
  = label_tag :entertainment, "<span></span>entertainment".html_safe, class: 'checkbox-label'

.checkbox-wrapper.checked
  = check_box_tag 'categories[]', "app", true, class: 'checkbox-filter categories'
  = label_tag :app, "<span></span>app".html_safe, class: 'checkbox-label'

.checkbox-wrapper.checked
  = check_box_tag 'categories[]', "concept", true, class: 'checkbox-filter categories'
  = label_tag :concept, "<span></span>concept".html_safe, class: 'checkbox-label'


%h2.checkbox-title Features

.checkbox-wrapper
  = check_box_tag 'players_free', "free", false, class: 'checkbox-filter genres'
  = label_tag :players_free, '<span></span>free'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'players_paid', "paid", false, class: 'checkbox-filter genres'
  = label_tag :players_paid, '<span></span>paid'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'players_single_player', "single-player", false, class: 'checkbox-filter genres'
  = label_tag :players_single_player, "<span></span>single player".html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'players_multi_player', "multi-player", false, class: 'checkbox-filter genres'
  = label_tag :players_multi_player, '<span></span>multi-player'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'players_internet_required', "internet-required", false, class: 'checkbox-filter genres'
  = label_tag :players_internet_required, '<span></span>internet required'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'players_gamepad_required', "gamepad-required", false, class: 'checkbox-filter genres'
  = label_tag :players_gamepad_required, '<span></span>gamepad required'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'players_gamepad_support', "gamepad-support", false, class: 'checkbox-filter genres'
  = label_tag :players_gamepad_support, '<span></span>gamepad support'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'players_touchpad_support', "touchpad-support", false, class: 'checkbox-filter genres'
  = label_tag :players_touchpad_support, '<span></span>touchpad support'.html_safe, class: 'checkbox-label'


%h2.checkbox-title Genres

.checkbox-wrapper
  = check_box_tag 'genre_action', "action", false, class: 'checkbox-filter genres'
  = label_tag :genre_action, '<span></span>action'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_adventure', "adventure", false, class: 'checkbox-filter genres'
  = label_tag :genre_adventure, '<span></span>adventure'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_arcade', "arcade", false, class: 'checkbox-filter genres'
  = label_tag :genre_arcade, '<span></span>arcade'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_casual', "casual", false, class: 'checkbox-filter genres'
  = label_tag :genre_casual, '<span></span>casual'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_educational', "educational", false, class: 'checkbox-filter genres'
  = label_tag :genre_educational, '<span></span>educational'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_exploration', "exploration", false, class: 'checkbox-filter genres'
  = label_tag :genre_exploration, '<span></span>exploration'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_fighting', "fighting", false, class: 'checkbox-filter genres'
  = label_tag :genre_fighting, '<span></span>fighting'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_horror', "horror", false, class: 'checkbox-filter genres'
  = label_tag :genre_horror, '<span></span>horror'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_movie', "movie", false, class: 'checkbox-filter genres'
  = label_tag :genre_movie, '<span></span>movie'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_music', "music", false, class: 'checkbox-filter genres'
  = label_tag :genre_music, '<span></span>music'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_music_video', "music-video", false, class: 'checkbox-filter genres'
  = label_tag :genre_music_video, '<span></span>music video'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_narrative', "narrative", false, class: 'checkbox-filter genres'
  = label_tag :genre_narrative, '<span></span>narrative'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_productivity', "productivity", false, class: 'checkbox-filter genres'
  = label_tag :genre_productivity, '<span></span>productivity'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_puzzle', "puzzle", false, class: 'checkbox-filter genres'
  = label_tag :genre_puzzle, '<span></span>puzzle'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_simulation', "simulation", false, class: 'checkbox-filter genres'
  = label_tag :genre_simulation, '<span></span>simulation'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_shooter', "shooter", false, class: 'checkbox-filter genres'
  = label_tag :genre_shooter, '<span></span>shooter'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_sports', "sports", false, class: 'checkbox-filter genres'
  = label_tag :genre_sports, '<span></span>sports'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_strategy', "strategy", false, class: 'checkbox-filter genres'
  = label_tag :genre_strategy, '<span></span>strategy'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_racing', "racing", false, class: 'checkbox-filter genres'
  = label_tag :genre_racing, '<span></span>racing'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_rpg', "rpg", false, class: 'checkbox-filter genres'
  = label_tag :genre_rpg, '<span></span>rpg'.html_safe, class: 'checkbox-label'

.checkbox-wrapper
  = check_box_tag 'genre_utilities', "utilities", false, class: 'checkbox-filter genres'
  = label_tag :genre_utilities, '<span></span>utilities'.html_safe, class: 'checkbox-label'

app/views/games/_form.haml
%br
- @genres.each do |genre|
  = link_to genre, add_genre_path(genre), remote: true
  |

%br
%br
= link_to 'Single Player', add_genre_path('single-player'), remote: true
%br
= link_to 'Multi-Player', add_genre_path('multi-player'), remote: true
%br
= link_to 'gamepad required', add_genre_path('gamepad-required'), remote: true
%br
= link_to 'internet required', add_genre_path('internet-required'), remote: true
%br
= link_to 'gamepad support', add_genre_path('gamepad-support'), remote: true
%br
= link_to 'touchpad support', add_genre_path('touchpad-support'), remote: true
%br
= link_to 'free', add_genre_path('free'), remote: true
%br
= link_to 'paid', add_genre_path('paid'), remote: true

= form_for @game, html: { multipart: true } do |f|

  = f.label :name
  = f.text_field :name
  %br
  = f.label :developer
  = f.text_field :developer
  %br
  = f.label :price
  = f.text_field :price
  %br
  = f.label :detail
  = f.text_area :detail
  %br
  = f.label :date_developed
  = f.datetime_field :date_developed
  %br
  = f.label :genre_list
  = f.text_field :genre_list, size: 150
  %br
  = f.label :category
  = f.text_field :category
  %br
  = f.label :website
  = f.text_field :website
  %br
  = f.label :thumbnail
  = f.file_field :thumbnail
  %br
  = f.label :youtube_videos
  = f.text_area :youtube_videos
  %br
  = f.label :main_image
  = f.file_field :main_image
  %br
  = f.fields_for :attachment do |ff|
    %div
      = ff.label :image
      = ff.file_field :image, multiple: true

  = f.submit

app/views/games/_game_list.haml
- @games.each do |game|
  .col-xs-12.col-md-6.single-game
    = link_to (image_tag game.thumbnail.url, class: 'img-responsive main-image'), game
    / %h2.game-name= link_to game.name, game

= will_paginate @games, renderer: BootstrapPagination::Rails

app/views/games/add_genre.js.erb
var genre = "<%= j @genre %>"

value = $('#game_genre_list').val()
new_value = value + ', ' + genre
$('#game_genre_list').val(new_value)

app/views/games/edit.haml
Edit Form

= render 'form'

app/views/games/index.haml
.row
  .col-xs-3
    = render 'filter'
  .col-xs-9
    #result
      = render 'game_list'

app/views/games/index.js.erb
$('#result').html('')

$('#result').append("<%= j render 'game_list' %>")

app/views/games/link_index.haml
- @games.each do |game|
  = link_to game.name, game
  %br

app/views/games/new.haml
Create New Game


= render 'form'

app/views/games/show.haml
= image_tag @game.main_image.url(:large), class: 'img-responsive'

.row.games-show-wrapper
  .col-xs-6

    %h2.game-title= @game.name

    %p.center-text 
   
    = rating_for @game, "rating", enable_half: true, half_show: true, star_path: '/images/ratyrate'
    %br
    = @game.category.capitalize
    %br
    = @game.dollar_price
    %br
    More games by 
    = link_to @game.developer, developer_path(@game.developer)
    %br
    %a{ href: @game.full_url, target: '_blank' }= @game.full_url
    %br
    Released:
    = @game.date_developed.strftime("%b %d, %Y")
    %br
    .tag.price= @price_tag
    - @genre_tags.each do |genre|
      .tag.genre= genre
    - @feature_tags.each do |feature|
      .tag.feature= feature
    
    %br
    = @game.detail

  .col-xs-6#media-wrapper
    #slick
      - if @youtube_videos
        - @youtube_videos.each do |youtube_video|
          %iframe{ width: "567", height: "400", src: "//www.youtube.com/embed/#{youtube_video}", frameborder: "0", allowfullscreen: true, webkitAllowFullScreen: true, mozallowfullscreen: true }
      - if @game.attachments
        - @game.attachments.each do |attachment|
          %img.img-responsive{ src: attachment.image.url }
.row.games-show-wrapper
  .col-xs-12
    .comments
      / START DISQUS
      #disqus_thread
      :javascript
        /* * * CONFIGURATION VARIABLES * * */
        var disqus_shortname = 'vrmachine';
        
        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
      %noscript
        Please enable JavaScript to view the
        %a{:href => "https://disqus.com/?ref_noscript", :rel => "nofollow"} comments powered by Disqus.
      / END DISQUS