config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  root to: 'games#index'

  get '/posts/tags/:tag' => 'posts#index', as: :posts_tag
  get '/posts/new' => 'posts#new', as: :new_post
  post '/posts' => 'posts#create'
  get '/post/:id' => 'posts#show', as: :post
  delete '/post/:id' => 'posts#destroy'
  get '/post/:id/edit' => 'posts#edit', as: :edit_post
  patch '/post/:id' => 'posts#update'

  get '/gearvr' => 'games#index', as: :games
  get '/gearvr/new' => 'games#new', as: :new_game
  post '/gearvr' => 'games#create'
  get '/gearvr/:id' => 'games#show', as: :game
  get '/gearvr/:id/edit' => 'games#edit', as: :edit_game
  patch '/gearvr/:id' => 'games#update'
  delete '/gearvr/:id' => 'games#destroy'
  get '/add_genre/:genre' => 'games#add_genre', as: :add_genre

  get 'gearvr/developer/:developer' => 'developers#show', as: :developer

  get '/about-vrmachine' => 'pages#about'
  

end

app/views/layouts/application.haml
!!!
%html
  %head
    %title Gear VR Games
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

    %meta{:content => "oo8NXM2PsT4gJXuAPht_y_r7s3hUzxoQ_ejrskh8WKY", :name => "google-site-verification"}
    - if params[:action] == 'index'
      %meta{ content: "VRMachine is a GearVR search engine for games and experiences.  You can filter through genres, features and categories until you find the perfect GearVR game for you.", name: 'description'}

    %link{ href: 'https://fonts.googleapis.com/css?family=Ubuntu:700|Permanent+Marker', rel: 'stylesheet', type: 'text/css' }
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-78814739-1', 'auto');
      ga('send', 'pageview');
    %script{:async => "async", "data-sumo-site-id" => "a7bc94ffd217663146cc45f1d320b97e9246003c73dfc13f976f171394d5efb3", :src => "//load.sumome.com/"}
  %body.overflow-x-hidden{ class: params[:controller] + "-" + params[:action] }
    .row
      .col-xs-12.no-padding.site-nav
        = link_to image_tag("https://s3.amazonaws.com/vrlist/misc/logo.png", alt: "VRMachine - Your Gear VR Search Engine", class: 'logo'), root_url
        =# link_to 'Gear VR News', posts_tag_path('gear-vr-news'), class: 'nav-links'
        =# link_to 'Top 10 Gear VR Games', posts_tag_path('top-list'), class: 'nav-links'
        = link_to 'Search Gear VR', root_url, class: 'nav-links'
        = link_to 'Upcoming Gear VR Games', posts_tag_path('upcoming'), class: 'nav-links'
        = link_to 'About VRMachine', '/about-vrmachine', class: 'nav-links'

        - if current_user && current_user.email == 'yangsunwoo@gmail.com'
          = link_to 'New Game', new_game_path
          = link_to 'New Post', new_post_path

    .container
      = yield

app/views/layouts/full-width-post.haml
!!!
%html
  %head
    %title= @post.title + " | Upcoming Gear VR Games"
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = javascript_include_tag 'ratyrate.js'
    %link{ href: 'https://fonts.googleapis.com/css?family=Ubuntu:700|Permanent+Marker', rel: 'stylesheet', type: 'text/css' }
    %script{:async => "async", "data-sumo-site-id" => "a7bc94ffd217663146cc45f1d320b97e9246003c73dfc13f976f171394d5efb3", :src => "//load.sumome.com/"}
    %meta{:content => "#{@post.content}", :name => "description"}/
  %body

    .container.container-full
      .row
        .col-xs-12.no-padding.site-nav
          = link_to image_tag("https://s3.amazonaws.com/vrlist/misc/logo.png", alt: "VRMachine - Your Gear VR Search Engine", class: 'logo'), root_url
          = link_to 'Search Gear VR', root_url, class: 'nav-links'
          = link_to 'Upcoming Gear VR Games', posts_tag_path('upcoming'), class: 'nav-links'
          = link_to 'About VRMachine', '/about-vrmachine', class: 'nav-links'
          - if current_user && current_user.email == 'yangsunwoo@gmail.com'
            = link_to 'Edit Post', edit_post_path(@post)
            = link_to 'Destroy Post', @post, method: :delete, confirm: 'You sure boya?'
          
      = yield

app/views/layouts/full-width.haml
!!!
%html
  %head
    %title= @game.name + " | Gear VR Games"
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = javascript_include_tag 'ratyrate.js'
    %link{ href: 'https://fonts.googleapis.com/css?family=Ubuntu:700|Permanent+Marker', rel: 'stylesheet', type: 'text/css' }
    %script{:async => "async", "data-sumo-site-id" => "a7bc94ffd217663146cc45f1d320b97e9246003c73dfc13f976f171394d5efb3", :src => "//load.sumome.com/"}
    %meta{:content => "#{@game.detail}", :name => "description"}/
  %body

    .container.container-full
      .row
        .col-xs-12.no-padding.site-nav
          = link_to image_tag("https://s3.amazonaws.com/vrlist/misc/logo.png", alt: "VRMachine - Your Gear VR Search Engine", class: 'logo'), root_url
          = link_to 'Search Gear VR', root_url, class: 'nav-links'
          = link_to 'About VRMachine', '/about-vrmachine', class: 'nav-links'
          - if current_user && current_user.email == 'yangsunwoo@gmail.com'
            = link_to 'Edit Game', edit_game_path(@game)
            = link_to 'Destroy Game', @game, method: :delete, confirm: 'You sure boya?'
          
      = yield